# Generated by Django 3.1.6 on 2021-03-29 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0002_auto_20210329_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='code_domain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buy',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buy',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buy',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buy',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rent',
            name='code_domain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rent',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='buy',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.image'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Domain.image'),
        ),
    ]
